services:
    my-sql:
        build:
            context: ./mysql
        ports:
            - "3306:3306"

    server:
        build:
            context: ./server
        ports:
            - "3040:3040"
        depends_on:
            - my-sql

    client:
        build:
            context: ./client
        ports:
            - "8080:8080"
        depends_on:
            - server
