export const catScores = {
    "Assembly:": 1.2,
    "Calibration:": 1,
    "Can Not Duplicate": 0,
    "Customer requirement": 1,
    "Damage": 1.75,
    "Document": 1.2,
    "electrical": 1.5,
    "Engineering": 2,
    "Hardware": 1.1,
    "HT": 1.3,
    "Infrastructure": 1.75,
    "Inspection Optics": 1.5,
    "Intgreation": 1.4,
    "low temp": 1.3,
    "Mechanical": 1.7,
    "No Problem": 0,
    "Optical": 1.2,
    "PERFORM ECO / FCO": 0,
    "RT": 1.1,
    "Software": 1.05,
    "TE CALL NO ": 1.1,
    "Tester": 1.3,
    "Workmanship": 1.4,
}

export const repActScores = {
    "Broken component": 1.4,
    "Cable Issue": 1.1,
    "Changed Test Equipment": 1,
    "Cleaning": 1.05,
    "Component Issue": 1.1,
    "D/A": 1.2,
    "Documentation correction": 1.05,
    "Fixed Test Equipment": 1,
    "Missing componet": 2,
    "No repair action was taken": 0,
    "Preform customer requirment": 1,
    "Preform ECO": 0,
    "Preform UPGRAGE": 0.5,
    "Re Calibration": 0.75,
    "Reassembly": 1.3,
    "Repair": 1.75,
    "Repair Infrastructure": 2,
    "Replace wrong component": 2.5,
    "Replaced SRU": 2,
    "Replaced/add Component": 1.8,
    "Reprograming": 1.1,
    "Retest": 1.1,
    "Rework": 1.5,
    "TESTER SOFTWER STUCK": 1.5,
}